### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by northkode** [inertiajs/inertiajs.com#15] opened 2019-10-07 23:40 UTC
Is there plans to support Django? 
I dont see an offical adapter, yet i believe i saw some where you mentioned this would work with it?

**Comment by reinink** [comment] 2019-10-08 00:45
I know @jsbeckr did some work quite a while ago on a [Django adapter](https://github.com/jsbeckr/inertia-django), but that's going to be pretty out of date at this point.

And yes, I'd love to offer an Django adapter. The issue is that I need community support for languages and frameworks I am not an expert in.

So, I guess what I'm saying is, if someone feels like they have the chops to put together a rock-solid adapter for whatever framework they use, we're open to putting that under the official Inertia namespace.

**Comment by northkode** [comment] 2019-10-08 01:10
You have a discord channel? 
I might be able to offer some help.

**Comment by reinink** [comment] 2019-10-08 01:11
> You have a discord channel?

Amazing!

> I might be able to offer some help.

[Sure do.](https://discord.gg/gwgxN8Y)

**Comment by robsontenorio** [comment] 2020-03-03 14:05
Django adapter has been archived by author. @reinink any plans in the future?

**Comment by Juhlinus** [comment] 2020-03-03 14:42
@robsontenorio Check out this PingCRM which has been posted on our Discord.

https://github.com/zodman/django-inertia-demo

**Comment by reinink** [comment] 2020-08-20 17:28
Hey folks, I'm going to close this issue, since it doesn't really pertain to the Inertia.js website. 👍

**Closed by reinink** 2020-08-20 17:28 UTC
